# Generated by Django 3.2.3 on 2021-06-04 13:00

from django.db import migrations
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagemodel',
            name='body',
            field=encrypted_model_fields.fields.EncryptedCharField(),
        ),
    ]
