# Generated by Django 3.2.3 on 2021-06-16 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_title',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
